# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: ubuntu

# Also define 'vault_users' (`group_vars/staging/vault.yml`, `group_vars/production/vault.yml`)
users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      - "{{ lookup('file', '~/.ssh/oss.pub', errors='ignore') }}"
      - "{{ lookup('file', '~/.ssh/id_ed25519.pub', errors='ignore') }}"
      - "{{ lookup('file', '~/.ssh/gitanjaan.pub', errors='ignore') }}"
      - "{{ lookup('file', '~/.ssh/gitanjaan', errors='ignore') }}"
      - https://github.com/anjaan7664.keys
      # - https://github.com/username.keys
  - name: "{{ admin_user }}"
    groups:
      - sudo
    keys:
      - "{{ lookup('file', '~/.ssh/oss.pub', errors='ignore') }}"
      - "{{ lookup('file', '~/.ssh/gitanjaan.pub', errors='ignore') }}"
      - "{{ lookup('file', '~/.ssh/gitanjaan', errors='ignore') }}"
      - https://github.com/anjaan7664.keys
      # - https://github.com/username.keys

web_user: web
web_group: www-data
web_sudoers:
  - "/usr/sbin/service php{{ php_version }}-fpm *"
