# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  oss.uatwebsite.live:
    site_hosts:
      - canonical: oss.uatwebsite.live
        redirects:
          - www.oss.uatwebsite.live
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@oss.uatwebsite.live
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    xmlrpc:
      enabled: false
